### Gerenciadores de Contexto

Aposto que as primeiras perguntas que surgem ao falar deste assunto s√£o. O que √©? E para que serve?

Bom, vamos pensar em funcionalides que devemos ficar atentos √† todas as etapas, principalmente a final. Parece um pouco estranho mas eu explico. 

√â comum precisarmos, por exemplo, manipular um arquivo, se comunicar com banco de dados ou fazer lock em threads. Mas voc√™ pode perceber o que essas atividades tem em comum? Para todas devemos ficar atentos a finaliza√ß√£o depois do uso. 

Vejamos, √© preciso lembrar de fechar um arquivo ap√≥s a manipula√ß√£o, fechar a conex√£o com o banco ap√≥s o uso e dar unlock em threads.


## Bloco Try

Vamos entender melhor o bloco 'try' no Python

- try: Tenta executar um c√≥dido
- except: Executa caso haja falha do c√≥digo que est√° no try
- finally: Esse bloco sempre ser√° executado

Vejamos um exemplos simples:

```python
try:
    print("Fa√ßa algo aqui")
except:
    print("Fa√ßa algo caso d√™ algo errado no bloco 'try'")
finally:
    print("Sempre ir√° ser executado")

```

Retono:

```
Fa√ßa algo aqui
Sempre ir√° ser executado

```

Percebam que uma coisa interessante aqui, temos um bloco que tentar√° algo, e tamb√©m um bloco que sempre ser√° executado. √â esse o princ√≠pio para os Gerenciadores de contexo. 

Vamos pegar o exemplo da manupula√ß√£o de arquivos. Vamos abrir um arquivo mas ao mesmo tempo garantir que iremos fecha-lo. Agora temos o seguinte c√≥digo.

```python
try:
    print("Abrindo um arquivo")
    arquivo = open('teste.txt', 'w', encoding='utf-8')
    arquivo.write("Oi")
except Exception as e:
    print("Erro ao tentar escrever no arquivo:", e)
finally:
    print("Fechando Arquivo")
    arquivo.close()

```

Retono:

```
Abrindo um arquivo
Fechando Arquivo

```

Percebam que agora podemos ficar tranquilos em rela√ß√£o a deixar o arquivo aberto por qualquer motivo que venha ocorrer. Mas vamos melhorar uma pouco mais essa idea. Afinal, Gerenciadores de Contexto est√£o aqui para isso üòâ

## Classes e m√©todos m√°gicos

OBS: Para entendermos e criamos nossos pr√≥prios gerenciadores, vamos trabalhar um pouco com classes. Ent√£o vamos l√°.

O Python nos fornece 2 m√©todos m√°gicos para trabalhar com os Gerenciadores de Contexto. S√£o eles: 

- \_\_enter__ : Responsavel por retornar o 'contexto', vamos pensar no arquivo.
- \_\_exit__ : Responsavel por receber as poss√≠veis exe√ß√µes que podem surgir e por finalizar a atividade (equivalente a jun√ß√£o do bloco except e finally que j√° vimos)

Para exemplificar, vamos de c√≥digo: 

```python
class MeuGerenciador:
    def __init__(self, nome_arquivo, modo, encoding) -> None:
        print("Criando arquivo a ser manipulado")
        self.arquivo = open(nome_arquivo, modo, encoding=encoding)

    def __enter__(self):
        """
        Esse bloco ter√° seu retorno atribuido a vari√°vel criada ap√≥s a palavra 'as'
        """
        print("Devolvendo arquivo para a utiliza√ß√£o")
        return self.arquivo

    def __exit__(self, tipo, valor, traceback):
        """
        Esse bloco sempre ser√° executado ao sa√≠rmos do gerenciador
        Caso ocorra um erro temos o valor, tipo e traceback que recebemos como par√¢metro
        """
        print("Fechando arquivo e saindo do gerenciador")
        self.arquivo.close()

```

Bom agora vamos ver como fica a utiliza√ß√£o dessa classe.

```python
with MeuGerenciador("teste.txt", "w", encoding="utf-8") as arquivo:
    arquivo.write("oi")

```

Retono:

```
Criando arquivo a ser manipulado
Devolvendo arquivo para a utiliza√ß√£o
Fechando arquivo e saindo do gerenciador

```

Agora ficou bem mais simples a utiliza√ß√£o. Vamos entender o que aconteceu aqui. 

A palavra 'with' basicamente acionou o m√©todo \_\_enter__ que criamos, e, por consequencia, utilizamos a palavra 'as' para criarmos a vari√°vel(ou seja, o 'contexto') que receber√° o retorno do m√©todo \_\_enter__. E quando que acionamos o m√©todo \_\_exit__ ? Quando ocorre um erro ou quando saimos do bloco 'with'. 

Ent√£o ficou f√°cil gerenciarmos coisas. Ou seja, podemos criar c√≥digos que iremos trabalhar em uma etapa e criar c√≥digos que ser√£o executados automaticamente depois. Legal n√©? üòä

Bem, isso foi apenas para entermos o funcionamento do gerenciadores de contexto, porque o pr√≥prio Python j√° traz um gerenciador de arquivos para n√≥s. Eu sei, eu sei "Se j√° tinha por que n√£o mostrou desde o in√≠cio?". Bom, a ideia era mostrar o que o Python nos fornece por baixo dos panos e tamb√©m fazer com que voc√™ consiga criar seus pr√≥prios gerenciadores. 

Ent√£o vamos ver como o Python traz de forma nativa o exemplo que criamos 

```python
with open("teste.txt", "w", encoding="utf-8") as arquivo:
    arquivo.write("oi")
```

Isso mesmo, a pr√≥pria fun√ß√£o open j√° possui um gerenciador de contexto. Ent√£o √© poss√≠vel utilizarmos das duas formas.

## Entendendo as Exce√ß√µes

Bom, chegamos at√© aqui e falta apenas entedermos como funciona as exce√ß√µes dos gerenciadores.

Para que possamos capturar uma exce√ß√£o no m√©todo \_\_exit__ precisamos j√° ter criado o contexo, ou seja, j√° ter atribuido valor √† variav√©l que foi criada com o retorno do m√©todo \_\_enter__. No nosso exemplo foi a vari√°vel 'arquivo'.

O m√©todo \_\_enter__ recebe 3 par√¢metros para manipula√ß√£o de erros. 

- tipo: A classe do tipo de erro. Erros que vem a partir da BaseException 
- valor: A mensagem de erro. Normalmente a mensagem que nos d√° a luz na hora do bug
- traceback: Um objeto do tipo traceback, nele temos os seguintes atributos:
  - tb_frame: Basicamente uma string com a mensagem de erro e seus detalhes do traceback
  - tb_lasti: √≠ndice da √∫ltima instru√ß√£o tentada em bytecode
  - tb_lineno: linha onde ocorreu o erro
  - tb_next: pr√≥ximo trackback, casa haja mais de 1

Caso n√£o haja nenhum erro durante a execu√ß√£o. Todos os par√¢metros ser√° atribuidos como None

Bem agora que entendemos melhor os erros. Vamos de exemplo. Ajustei a classe que criamos para for√ßamos os erros, executei o m√©todo write com 2 'e', dessa forma vamos ter um erro pois o m√©todo writee n√£o existe. Vejamos:

```python
class MeuGerenciador:
    def __init__(self, nome_arquivo, modo, encoding) -> None:
        print("criando arquivo a ser manipulado")
        self.arquivo = open(nome_arquivo, modo, encoding=encoding)

    def __enter__(self):
        """
        Esse bloco ter√° seu retorno atribuido a vari√°vel criada ap√≥s a palavra 'as'
        """
        print("devolvendo arquivo para a utiliza√ß√£o")
        return self.arquivo

    def __exit__(self, tipo, valor, traceback):
        """
        Esse bloco sempre ser√° executado ao sa√≠rmos do gerenciador
        caso ocorra um erro temos o valor, tipo e traceback que recebemos como par√¢metro
        """
        print("Capturando erros")
        print("tipo -> ", tipo)
        print("valor ->", valor)
        print("traceback frame ->", traceback.tb_frame)
        print("traceback √≠ndice ->", traceback.tb_lasti)
        print("traceback linha do erro ->", traceback.tb_lineno)
        print("traceback linha do erro ->", traceback.tb_next)
        self.arquivo.close()

```

Executando a classe com m√©todo 'writee'

```python
with MeuGerenciador("teste.txt", "w", encoding="utf-8") as arquivo:
    arquivo.writee("oi")

```

Retorno: 

```
criando arquivo a ser manipulado
devolvendo arquivo para a utiliza√ß√£o
Capturando erros
tipo ->  <class 'AttributeError'>
valor -> '_io.TextIOWrapper' object has no attribute 'writee'
traceback frame -> <frame at 0x000001FBC34AB050, file 'c:\\DevNew\\dev-to\\2-gerenciador-contexto\\code.py', line 43, code <module>>
traceback √≠ndice -> 32
traceback linha do erro -> 43
traceback linha do erro -> None
Traceback (most recent call last):
  File "c:\DevNew\dev-to\2-gerenciador-contexto\code.py", line 43, in <module>
    arquivo.writee("oi")
AttributeError: '_io.TextIOWrapper' object has no attribute 'writee'

```
<br>

Agora sim vimos os detalhes da manipula√ß√£o desse recurso incr√≠vel!

## Conclus√£o 

Bem, Espero ter ajudado no entendimento de gerenciador de contexo. Tentei detalhar ao m√°ximo essa jornada. Mas vamos lembrar que √© muito √∫til a utiliza√ß√£o desse recurso.

Se esse Post foi √∫til para voc√™, curta e compartilhe. 